version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: IMAGE_REPO_NAME
    IMAGE_TAG: IMAGE_TAG

phases:
  install:
    runtime-version: 
      docker: 18
  pre_build:
    commands:
      - echo Login To Dockerhub
      - echo "Debugging environment variables"
      - echo "IMAGE_REPO_NAME: $IMAGE_REPO_NAME"
      - echo "IMAGE_TAG: $IMAGE_TAG"
      - ls -al   # Check if Dockerfile is in the correct directory
  build:
    commands:
      - echo Starting The Build
      - docker login --username msshoaib2255457 --password 177y1a0464
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
