version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: msshoaib2255457/nginx-webserver # Replace with your DockerHub repo name
    IMAGE_TAG: latest               # Replace with your desired tag (you can dynamically set this)

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - echo "Logging into DockerHub..."
      - docker login --username msshoaib2255457 --password 177y1a0464
      - echo "Debugging environment variables..."
      - echo "IMAGE_REPO_NAME: $IMAGE_REPO_NAME"
      - echo "IMAGE_TAG: $IMAGE_TAG"
      - echo "Listing files in the build context:"
      - ls -al .
      - echo "Checking for Dockerfile:"
      - if [ ! -f Dockerfile ]; then echo "Dockerfile not found!"; exit 1; fi

  build:
    commands:
      - echo "Starting the Docker build..."
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image..."
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
